server:
  port:
    8100

bot:
  username: anonimka_ru_chatbot
  token: 7221258678:AAELInVCxyVbqlAkJyLfAhTMkJnWHjra-Qo

spring:
  kafka:
    bootstrap-servers: localhost:9095
    producer:
      bootstrap-servers: localhost:9095
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable:
          idempotence: true

    consumer:
      bootstrap-servers: localhost:9095
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: messages-to-user-consumers
      properties:
        spring:
          json:
            trusted:
              packages: com.vlat.kafkaMessage

kafka:
  topics:
    text-message:
      name: text-message-topic
      partitions: 5
      replication-factor: 1
      min-insync-replicas: 1
    command-message:
      name: command-message-topic
      partitions: 3
      replication-factor: 1
      min-insync-replicas: 1
    answer-message:
      name: answer-message-topic
      partitions: 5
      replication-factor: 1
      min-insync-replicas: 1
    file-message:
      name: file-message-topic
      partitions: 3
      replication-factor: 1
      min-insync-replicas: 1
