server:
  port:
    8101

spring:
  kafka:
    bootstrap-servers: localhost:9095
    producer:
      bootstrap-servers: localhost:9095
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable:
          idempotence: true


    consumer:
      bootstrap-servers: localhost:9095
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: messages-to-bot-consumers
      properties:
        spring:
          json:
            trusted:
              packages: com.vlat.kafkaMessage

kafka:
  topics:
    text-message:
      name: text-message-topic
    command-message:
      name: command-message-topic
    answer-message:
      name: answer-message-topic
